In [1]:
import pyanno
import numpy as np
import scipy as sp
import gss_complete_comparison as gc
reload(gss_complete_comparison)

ImportError: No module named gss_complete_comparison

Getting from database to datafile

In [312]:
gc.variablize_simpler("gss_variable_ques_no07.txt")

21461
6
{'1': 2, '3': 4, '2': 0, '5': 1, '4': 5, '6': 3}


Getting the data for each GSS question

In [2]:
from pyanno.annotations import AnnotationsContainer
#anno_vdep = AnnotationsContainer.from_file(missing_values=[-1], filename="GSSvariable_testSdependent.csv")
dev = np.loadtxt(fname="n7GSSvariable_testSdependent.csv", dtype=int, delimiter=",")
anno_dv = AnnotationsContainer.from_array(dev)

ind = np.loadtxt(fname="n7GSSvariable_testSindependent.csv", dtype=int, delimiter=",")
anno_iv = AnnotationsContainer.from_array(ind)

cent = np.loadtxt(fname="n7GSSvariable_testScentral.csv", dtype=int, delimiter=",")
anno_cv = AnnotationsContainer.from_array(cent)

cont = np.loadtxt(fname="n7GSSvariable_testScontrol.csv", dtype=int, delimiter=",")
anno_ctv = AnnotationsContainer.from_array(cont)

test = np.loadtxt(fname="testH.csv", dtype=int, delimiter=",")
anno_test = AnnotationsContainer.from_array(test)

IOError: [Errno 2] No such file or directory: 'testH.csv'

In [3]:
dev.shape
test.shape

NameError: name 'test' is not defined

In [9]:
anno_dv.annotations

array([[ 0, -1, -1,  1, -1,  1],
       [ 0, -1, -1,  0, -1,  0],
       [ 0, -1, -1,  1, -1,  0],
       ..., 
       [-1, -1, -1, -1,  0, -1],
       [-1, -1, -1, -1,  0, -1],
       [-1, -1, -1, -1,  0, -1]])

In [7]:
anno_dv.missing_values

[-1]

In [8]:
anno_dv.annotations.shape

(21461, 6)

Measuring agreement between coders

In [10]:
from pyanno.measures import pairwise_matrix, agreement, cohens_kappa, cohens_weighted_kappa, fleiss_kappa, krippendorffs_alpha, pearsons_rho, scotts_pi, spearmans_rho

In [11]:
print pairwise_matrix(cohens_kappa, anno_dv.annotations)

[[ 1.          0.62426874  0.46682841  0.44599604  0.16569888  0.36657805]
 [ 0.62426874  1.          0.53480937  0.52673854  0.3306905   0.59513211]
 [ 0.46682841  0.53480937  1.          0.50580068  0.42393752  0.49833997]
 [ 0.44599604  0.52673854  0.50580068  1.          0.46517493  0.47023754]
 [ 0.16569888  0.3306905   0.42393752  0.46517493  1.          0.66190749]
 [ 0.36657805  0.59513211  0.49833997  0.47023754  0.66190749  1.        ]]


In [12]:
xdevck = pairwise_matrix(cohens_kappa, anno_dv.annotations)
#xdevcwk = pairwise_matrix(cohens_weighted_kappa, anno_dv.annotations) # SAME as unweighted
#xdevka = pairwise_matrix(krippendorffs_alpha, anno_dv.annotations) # BROKEN
xdevpr = pairwise_matrix(pearsons_rho, anno_dv.annotations)
#xdevfk = fleiss_kappa(anno_dv.annotations, nclasses=2)

xindck = pairwise_matrix(cohens_kappa, anno_iv.annotations)
xindpr = pairwise_matrix(pearsons_rho, anno_iv.annotations)

xcenck = pairwise_matrix(cohens_kappa, anno_cv.annotations)
xcenpr = pairwise_matrix(pearsons_rho, anno_cv.annotations)

xconck = pairwise_matrix(cohens_kappa, anno_ctv.annotations)
xconpr = pairwise_matrix(pearsons_rho, anno_ctv.annotations)

In [13]:
nondiag = (np.eye(6)-np.ones(6))*-1.0

Test the comparison of students

In [14]:
print np.average(xdevck,weights=nondiag)
#print np.average(xdevcwk, weights=nondiag) #SAME AS UNWEIGHTED KAPPA
#print np.average(xdevka, weights=nondiag)
print np.average(xdevpr, weights=nondiag)

print np.average(xindck, weights=nondiag)
print np.average(xindpr, weights=nondiag)

print np.average(xcenck, weights=nondiag)
print np.average(xcenpr, weights=nondiag)

print np.average(xconck, weights=nondiag)
print np.average(xconpr, weights=nondiag)

0.472142584454
0.514240727822
0.45296278237
0.475965268669
0.270823768698
0.315140498284
0.328334778759
0.39458527792


Bring in merge data: author_dependent, mode_dependent, author_independent, mode_independent, author_central, mode_central, author_control, mode_control, author_don't_know, mode_don't_know

In [15]:
mergedata = np.loadtxt(fname="gss_mergedataC.txt", dtype=int, delimiter="\t")

In [16]:
anno_merge_dep = AnnotationsContainer.from_array(mergedata[:,0:2])
anno_merge_ind = AnnotationsContainer.from_array(mergedata[:,2:4])
anno_merge_cen = AnnotationsContainer.from_array(mergedata[:,4:6])
anno_merge_con = AnnotationsContainer.from_array(mergedata[:,6:8])
anno_merge_dkn = AnnotationsContainer.from_array(mergedata[:,8:10])

In [17]:
print "Dependent variable"
print cohens_kappa(anno_merge_dep.annotations[:,0], anno_merge_dep.annotations[:,1])
print pearsons_rho(anno_merge_dep.annotations[:,0], anno_merge_dep.annotations[:,1])

print "Independent variable"
print cohens_kappa(anno_merge_ind.annotations[:,0], anno_merge_ind.annotations[:,1])
print pearsons_rho(anno_merge_ind.annotations[:,0], anno_merge_ind.annotations[:,1])

print "Central variable"
print cohens_kappa(anno_merge_cen.annotations[:,0], anno_merge_cen.annotations[:,1])
print pearsons_rho(anno_merge_cen.annotations[:,0], anno_merge_cen.annotations[:,1])

print "Control variable"
print cohens_kappa(anno_merge_con.annotations[:,0], anno_merge_con.annotations[:,1])
print pearsons_rho(anno_merge_con.annotations[:,0], anno_merge_con.annotations[:,1])

Dependent variable
0.374431105795
0.385634372036
Independent variable
0.543069016464
0.552997494177
Central variable
-0.0640171895485
-0.0888764431926
Control variable
0.281517249918
0.282392375746


Now for the assessment of the relative values of authors, then student coders

In [18]:
print "Dependent"
print np.average(anno_merge_dep.annotations[:,0])
print np.average(anno_merge_dep.annotations[:,1])

print "Independent"
print np.average(anno_merge_ind.annotations[:,0])
print np.average(anno_merge_ind.annotations[:,1])

print "Central"
print np.average(anno_merge_cen.annotations[:,0])
print np.average(anno_merge_cen.annotations[:,1])

print "Control"
print np.average(anno_merge_con.annotations[:,0])
print np.average(anno_merge_con.annotations[:,1])

Dependent
0.476391231029
0.358347386172
Independent
0.237774030354
0.313659359191
Central
0.35328836425
0.751264755481
Control
0.0817875210793
0.0944350758853


In [19]:
mergedata

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
posterior_check = np.loadtxt(fname="gss_mergeposteriors_full_cohensU.csv", dtype=int, delimiter=",")

IOError: [Errno 2] No such file or directory: 'gss_mergeposteriors_full_cohensU.csv'

In [21]:
anno_posts = AnnotationsContainer.from_array(posterior_check)

NameError: name 'posterior_check' is not defined

In [22]:
print "Dependent variable"
print pairwise_matrix(cohens_kappa, anno_posts.annotations[:,0:3])
print pairwise_matrix(pearsons_rho, anno_posts.annotations[:,0:3])

print "Independent variable"
print pairwise_matrix(cohens_kappa, anno_posts.annotations[:,3:6])
print pairwise_matrix(pearsons_rho, anno_posts.annotations[:,3:6])

print "Central variable"
print pairwise_matrix(cohens_kappa, anno_posts.annotations[:,6:9])
print pairwise_matrix(pearsons_rho, anno_posts.annotations[:,6:9])

print "Control variable"
print pairwise_matrix(cohens_kappa, anno_posts.annotations[:,9:12])
print pairwise_matrix(pearsons_rho, anno_posts.annotations[:,9:12])



Dependent variable


NameError: name 'anno_posts' is not defined

In [23]:
print anno_posts.annotations.shape


NameError: name 'anno_posts' is not defined

Hacking the Model A (by adding two blank columns)

In [24]:
from pyanno.models import ModelA
from pyanno.models import ModelB
from pyanno.models import ModelBt

In [25]:
print dev.shape

(21461, 6)


In [26]:
negs2 = np.ones((21464, 2), dtype=np.int)*(-1)

In [27]:
devA = np.concatenate((dev, negs2), axis=1)
devA

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [28]:
anno_dvA = AnnotationsContainer.from_array(devA)

NameError: name 'devA' is not defined

In [29]:
model_devA = ModelA.create_initial_state(2)

In [30]:
model_devA.theta

array([ 0.70734203,  0.79809988,  0.93681494,  0.93366036,  0.87633399,
        0.61793138,  0.72727604,  0.93706565])

In [31]:
model_devA.map(anno_dvA.annotations)

NameError: name 'anno_dvA' is not defined

In [324]:
model_dvB = ModelB.create_initial_state(2, 6)
print model_dvB.pi
print model_dvB.log_likelihood(anno_dv.annotations)

[ 0.00265466  0.99734534]
-67698.5649797


In [325]:
model_dvB.map(anno_dv.annotations)
print model_dvB.pi
print model_dvB.log_likelihood(anno_dv.annotations)

[ 0.69455487  0.30544513]
-25462.473635


In [326]:
# compute the posterior distribution over true annotations
posterior_dvB = model_dvB.infer_labels(anno_dv.annotations)
print posterior_dvB.shape
print anno_dv.annotations.shape
# each row show the probability of each label class for the
# corresponding item
print posterior

(21461, 2)
(21461, 6)
[[ 0.99277483  0.00722517]
 [ 0.78378012  0.21621988]
 [ 0.99277483  0.00722517]
 ..., 
 [ 0.94992254  0.05007746]
 [ 0.94992254  0.05007746]
 [ 0.94992254  0.05007746]]


In [327]:
samples_dvB = model_dvB.sample_posterior_over_accuracy(anno_dv.annotations, 200, burn_in_samples=100, thin_samples=3)

In [328]:
# we can then compute a credible interval for the parameters:
ci_dv_mean = samples_dvB[0].mean(axis=0)
print ci_dv_mean

ci_dv_stdev = samples_dvB[0].std(axis=0)
print ci_dv_stdev
print ci_dv_stdev.shape

[[[ 0.9792372   0.0207628 ]
  [ 0.51505718  0.48494282]]

 [[ 0.96908844  0.03091156]
  [ 0.25949934  0.74050066]]

 [[ 0.98294352  0.01705648]
  [ 0.34690563  0.65309437]]

 [[ 0.93465367  0.06534633]
  [ 0.24001862  0.75998138]]

 [[ 0.69249657  0.30750343]
  [ 0.04553065  0.95446935]]

 [[ 0.86346201  0.13653799]
  [ 0.06878648  0.93121352]]]
[[[ 0.00223971  0.00223971]
  [ 0.01220077  0.01220077]]

 [[ 0.00318966  0.00318966]
  [ 0.01186946  0.01186946]]

 [[ 0.00311056  0.00311056]
  [ 0.01276822  0.01276822]]

 [[ 0.00468154  0.00468154]
  [ 0.01255932  0.01255932]]

 [[ 0.0068435   0.0068435 ]
  [ 0.00528945  0.00528945]]

 [[ 0.00713735  0.00713735]
  [ 0.00789741  0.00789741]]]
(6, 2, 2)


B estimates for other variables

In [267]:
#test
model_testB = ModelB.create_initial_state(2, 6)
print model_testB.log_likelihood(anno_test.annotations)
model_testB.map(anno_test.annotations)
print model_testB.pi
print model_testB.log_likelihood(anno_test.annotations)
print anno_test.annotations.shape
posterior_testB = model_testB.infer_labels(anno_test.annotations)
print posterior_testB.shape
samples_testB = model_testB.sample_posterior_over_accuracy(anno_test.annotations, 200, burn_in_samples=100, thin_samples=3)
ci_test_mean = samples_testB[0].mean(axis=0)
print ci_test_mean

-160.763707314
[  9.20933481e-20   1.00000000e+00]
-48.9756711394
(48, 6)
(48, 2)
[[[ 0.79728625  0.20271375]
  [ 0.12733022  0.87266978]]

 [[ 0.79697037  0.20302963]
  [ 0.09347859  0.90652141]]

 [[ 0.80834214  0.19165786]
  [ 0.50120866  0.49879134]]

 [[ 0.79463979  0.20536021]
  [ 0.07220905  0.92779095]]

 [[ 0.80135186  0.19864814]
  [ 0.35913689  0.64086311]]

 [[ 0.79556005  0.20443995]
  [ 0.12893161  0.87106839]]]


In [329]:
#indepedent variables
model_ivB = ModelB.create_initial_state(2, 6)
print model_ivB.log_likelihood(anno_iv.annotations)
model_ivB.map(anno_iv.annotations)
print model_ivB.pi
print model_ivB.log_likelihood(anno_iv.annotations)
print anno_iv.annotations.shape
posterior_ivB = model_ivB.infer_labels(anno_iv.annotations)
print posterior_ivB.shape
samples_ivB = model_ivB.sample_posterior_over_accuracy(anno_iv.annotations, 200, burn_in_samples=100, thin_samples=3)
ci_iv_mean = samples_ivB[0].mean(axis=0)
print ci_iv_mean

#central variables
model_cvB = ModelB.create_initial_state(2, 6)
print model_cvB.log_likelihood(anno_cv.annotations)
model_cvB.map(anno_cv.annotations)
print model_cvB.pi
print model_cvB.log_likelihood(anno_cv.annotations)
print anno_cv.annotations.shape
posterior_cvB = model_cvB.infer_labels(anno_cv.annotations)
print posterior_cvB.shape
samples_cvB = model_cvB.sample_posterior_over_accuracy(anno_cv.annotations, 200, burn_in_samples=100, thin_samples=3)
ci_cv_mean = samples_cvB[0].mean(axis=0)
print ci_cv_mean

#control variables
model_ctvB = ModelB.create_initial_state(2, 6)
print model_ctvB.log_likelihood(anno_ctv.annotations)
model_ctvB.map(anno_ctv.annotations)
print model_ctvB.pi
print model_ctvB.log_likelihood(anno_ctv.annotations)
print anno_ctv.annotations.shape
posterior_ctvB = model_ctvB.infer_labels(anno_ctv.annotations)
print posterior_ctvB.shape
samples_ctvB = model_ctvB.sample_posterior_over_accuracy(anno_iv.annotations, 200, burn_in_samples=100, thin_samples=3)
ci_ctv_mean = samples_ctvB[0].mean(axis=0)
print ci_ctv_mean

-36878.2151801
[ 0.61093546  0.38906454]
-28620.6652325
(21461, 6)
(21461, 2)
[[[ 0.97094674  0.02905326]
  [ 0.347209    0.652791  ]]

 [[ 0.93759217  0.06240783]
  [ 0.05351226  0.94648774]]

 [[ 0.65848424  0.34151576]
  [ 0.21055995  0.78944005]]

 [[ 0.53664141  0.46335859]
  [ 0.03089476  0.96910524]]

 [[ 0.87482742  0.12517258]
  [ 0.10027926  0.89972074]]

 [[ 0.89151014  0.10848986]
  [ 0.09008307  0.90991693]]]
-37461.158059
[ 0.23988844  0.76011156]
-25034.9185558
(21461, 6)
(21461, 2)
[[[ 0.89027037  0.10972963]
  [ 0.06879129  0.93120871]]

 [[ 0.78180864  0.21819136]
  [ 0.05686058  0.94313942]]

 [[ 0.99179932  0.00820068]
  [ 0.84064577  0.15935423]]

 [[ 0.95074227  0.04925773]
  [ 0.4548972   0.5451028 ]]

 [[ 0.67409391  0.32590609]
  [ 0.05685613  0.94314387]]

 [[ 0.59001192  0.40998808]
  [ 0.09554745  0.90445255]]]
-25014.405559
[ 0.83068326  0.16931674]
-19415.7020352
(21461, 6)
(21461, 2)
[[[ 0.97112284  0.02887716]
  [ 0.3481723   0.6518277 ]]

 [[ 0.93718801

Now for the Bt models

In [305]:
model_dvBt = ModelBt.create_initial_state(2, 7)

#print model_dvB.pi
print model_dvBt.log_likelihood(anno_dv.annotations)

-31538.9929872


In [306]:
model_dvBt.map(anno_dv.annotations)
print model_dvBt.log_likelihood(anno_dv.annotations)

-27730.0309218


In [250]:
# compute the posterior distribution over true annotations
posterior_dvBt = model_dvBt.infer_labels(anno_dv.annotations)
print posterior_dvBt.shape
# each row show the probability of each label class for the
# corresponding item
print posterior_dvBt

(1755, 2)
[[ 0.82409515  0.17590485]
 [ 0.00264552  0.99735448]
 [ 0.98696724  0.01303276]
 ..., 
 [ 0.02170252  0.97829748]
 [ 0.58034303  0.41965697]
 [ 0.02170252  0.97829748]]


In [251]:
samples_dvBt = model_dvBt.sample_posterior_over_accuracy(anno_dv.annotations, 200, burn_in_samples=100, thin_samples=3)

In [252]:
# we can then compute a credible interval for the parameters:
ci_dv_meanBt = samples_dvBt.mean(axis=0)
print ci_dv_meanBt

ci_dv_stdevBt = samples_dvBt.std(axis=0)
print ci_dv_stdevBt
print ci_dv_stdevBt.shape

[ 0.84109423  0.90866046  0.26758786  0.54102117  0.87461539  0.80715753
  0.59200203]
[ 0.01487131  0.01522477  0.02900773  0.02439919  0.01449132  0.02028668
  0.07231733]
(7,)


Bt estimates for other variables

In [243]:
model_ivBt = ModelBt.create_initial_state(2, 7)
print model_ivBt.log_likelihood(anno_iv.annotations)
model_ivBt.map(anno_iv.annotations)
print model_ivBt.log_likelihood(anno_iv.annotations)
posterior_ivBt = model_ivBt.infer_labels(anno_iv.annotations)
samples_ivBt = model_ivBt.sample_posterior_over_accuracy(anno_iv.annotations, 200, burn_in_samples=100, thin_samples=3)
ci_iv_meanBt = samples_ivBt.mean(axis=0)
print ci_iv_meanBt

model_cvBt = ModelBt.create_initial_state(2, 7)
print model_cvBt.log_likelihood(anno_cv.annotations)
model_cvBt.map(anno_cv.annotations)
print model_cvBt.log_likelihood(anno_cv.annotations)
posterior_cvBt = model_cvBt.infer_labels(anno_cv.annotations)
samples_cvBt = model_cvBt.sample_posterior_over_accuracy(anno_cv.annotations, 200, burn_in_samples=100, thin_samples=3)
ci_cv_meanBt = samples_cvBt.mean(axis=0)
print ci_cv_meanBt

model_ctvBt = ModelBt.create_initial_state(2, 7)
print model_ctvBt.log_likelihood(anno_ctv.annotations)
model_ctvBt.map(anno_ctv.annotations)
print model_ctvB.log_likelihood(anno_ctv.annotations)
posterior_ctvBt = model_ctvBt.infer_labels(anno_ctv.annotations)
samples_ctvBt = model_ctvBt.sample_posterior_over_accuracy(anno_ctv.annotations, 200, burn_in_samples=100, thin_samples=3)
ci_ctv_meanBt = samples_ctvBt.mean(axis=0)
print ci_ctv_meanBt

-2061.54848941
-1790.00853363
[ 0.98495093  0.94276877  0.87282053  0.83148504  0.64356573  0.71616554
  0.74055411]
-1903.57018961
-1632.30560108
[ 0.95493278  0.91219124  0.87459821  0.79022961  0.81851628  0.9233728
  0.89892025]
-1280.83504527
-20.0239887563
[ 0.99887538  0.99840864  0.99526555  0.88654119  0.99809589  0.99758836
  0.85513793]


Package up into something testable against author data

In [271]:
print posterior_dvB.shape
print posterior_ivB.shape
print posterior_cvB.shape
print posterior_ctvB.shape
print posterior_dvBt.shape
print posterior_ivBt.shape
print posterior_cvBt.shape
print posterior_ctvBt.shape

(1755, 2)
(1755, 2)
(1755, 2)
(1755, 2)
(1755, 2)
(1755, 2)
(1755, 2)
(1755, 2)


[[ 0.97228992  0.02771008]
 [ 0.00159335  0.99840665]
 [ 0.9983923   0.0016077 ]
 ..., 
 [ 0.11945379  0.88054621]
 [ 0.74139328  0.25860672]
 [ 0.11945379  0.88054621]]


In [330]:
predicted_annotations = np.concatenate((posterior_dvB, posterior_ivB, posterior_cvB, posterior_ctvB), axis=1) # posterior_dvBt, posterior_ivBt, posterior_cvBt, posterior_ctvBt), axis=1)

In [331]:
predicted_annotations.shape

(21461, 8)

In [332]:
np.savetxt("B_outputs.txt", predicted_annotations, delimiter='\t')

Data gathered from the following query: "mysql lanl -e "Select dependent, posterior_dvB, posterior_dvBt, independent, posterior_ivB, posterior_ivBt, central, posterior_cvB, posterior_cvBt, control, posterior_ctvB, posterior_ctvBt, dontknow from gss_answers_auth a, gss_answers_posteriors b where a.article_id=b.article_id and a.variable=b.variable" > gss_mergeposteriors.txt"

In [ ]:
mergeposteriors = np.loadtxt(fname="gss_mergeposteriors.txt", dtype=float, delimiter="\t")